### ISSUE TITLE
add comment with credit for contact form

### ISSUE THREAD

**Issue by greglinch** [szs10/Final-Project#16]
Ideally with a link to the tutorial/resource/inspiration you adapted it from:

https://github.com/szs10/Final-Project/commit/2d279b3b4893ea0ac80a4a33188f3b49df3e0465#diff-2793ccaab55e0b1424c254e14b1dc534R39

**Comment by szs10** [comment]
I'm sorry but I don't understand what you mean.

**Comment by greglinch** [comment]
@szs10 If you used a tutorial or sample code, please include a code comment crediting and linking to it.

**Comment by szs10** [comment]
Added comment with credit for contact form
