### ISSUE TITLE
fix margins on smaller screens

### ISSUE THREAD

**Issue by greglinch** [szs10/Final-Project#18]
The text goes all the way to the edge on smaller screens currently:

<img width="302" alt="Screen Shot 2019-04-24 at 11 52 27 PM" src="https://user-images.githubusercontent.com/327783/56708789-13157880-66ec-11e9-8a1a-05b15d6fa796.png">

<img width="312" alt="Screen Shot 2019-04-24 at 11 52 34 PM" src="https://user-images.githubusercontent.com/327783/56708790-13157880-66ec-11e9-80ce-6f34d19b5fa3.png">

**Comment by szs10** [comment]
How can I do that? All the changes I add to the .css only apply to the homepage, rather than the custom page

**Comment by greglinch** [comment]
@szs10 Generally speaking, adding margins should do the trick. Specifically, if CSS changes aren't appearing on the custom pages, I'd first recommending making sure the right CSS file itself is loading on the custom pages. For example, by inspecting element or view source. If it is, then try making sure you're targeting the right classes or ids.

**Comment by szs10** [comment]
Fixed margins
