### ISSUE TITLE
Add keyword search feature?

### ISSUE THREAD

**Issue by sidlowsh** [szs10/Final-Project#2]
If you use the Reading List plug-in as an example, you could add custom taxonomies to your post types. You could then add keywords based on the various styles, eras, brands, countries, or clothing items to allow users to search for content relevant to them.

**Comment by szs10** [comment]
Thanks for your feedback! As for the requirements of the final projects I have enough customizations, therefore I don't think I will add one more. However, if I decide to continue working on this blog in the future, I will surely consider adding a keyword search feature :)
