### ISSUE TITLE
Reconsider font choices

### ISSUE THREAD

**Issue by sidlowsh** [szs10/Final-Project#3]
The white font on black pages is very fashionable, but a little hard to read, especially if the posts will be text-heavy. Consider increasing your font size or choosing a different color to allow for readability and decrease reader fatigue on mobile. 

Here's a link that may be useful: https://www.designworkplan.com/read/signage-and-color-contrast

**Comment by szs10** [comment]
Even though I truly appreciate your feedback, I think white font is the best option for a black background. There won't be a lot of text on the blog, I added content to the website and it is still easy to read.
